#!/bin/bash

echo "🔧 LangSmith Setup Guide"
echo "========================"
echo ""
echo "1. Go to https://smith.langchain.com and sign up/login"
echo "2. Create a new project or use an existing one"
echo "3. Go to Settings -> API Keys and create a new API key"
echo "4. Copy your API key and run:"
echo ""
echo "   export LANGCHAIN_TRACING_V2=true"
echo "   export LANGCHAIN_ENDPOINT=https://api.smith.langchain.com"
echo "   export LANGCHAIN_API_KEY=your_api_key_here"
echo "   export LANGCHAIN_PROJECT=your_project_name"
echo ""
echo "5. Add these to your .env file:"
echo ""
echo "LANGCHAIN_TRACING_V2=true"
echo "LANGCHAIN_ENDPOINT=https://api.smith.langchain.com"
echo "LANGCHAIN_API_KEY=your_api_key_here"
echo "LANGCHAIN_PROJECT=agents-demo"
echo ""
echo "6. Then run your agent and traces will appear in LangSmith!"
